### ISSUE TITLE
More informative messages when cli fails to launch.

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#27] opened 2022-07-04 07:14 UTC
While working on a feature, I saw
```
Error during startup:Error with response: Status { code: Unavailable, message: "error trying to connect: tcp connect error: Connection refused (os error 111)", source: Some(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))) }
If you repeatedly run into this issue, you might have to restore your wallet from your seed phrase.
```

This failure had nothing at all to do with the seed phrase, and a naive user wouldn't know this.

We should look at what failure messages are printed under what conditions, and probably improve them.

**Comment by zancas** [comment] 2022-07-22 21:55
One cause of that message is missing network parameters.

Fixed by running `zcutil/fetch_params.sh`

Another confusing message is the message printed on regtest launch, that is caused by the 0-block blockchain.

**Comment by zancas** [comment] 2024-07-09 04:38
@dannasessha are you available to test this to see if the error messages have improved?

If I don't hear back from you within 48 hours, I am going to close this as won't-fix.

**Closed** 2024-07-12 15:39 UTC
