### ISSUE TITLE
Ready for Halloween 🎃

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingolib#613] opened 2023-10-20 16:39 UTC
**Transactions disappearing 👻 from history and zero balance.**

I report here on zingolib because I think it has to do with zingolib rather than Zingo Mobile or Zingo PC.

Sometimes closing and opening Zingo after the wallet syncs causes these problems:

1. **Transactions disappear**

I have compared with other wallets and yes, zingo-cli, zingo mobile and zingo-pc sometimes show a number of transactions in the list and when closing and opening again, the list of transactions changes and some of them are not displayed.

Before:

![Screenshot_20231020-103912.jpg](https://github.com/zingolabs/zingolib/assets/37910384/a821920d-bf3c-45ab-8389-c6896e8eb691)

After:

![Screenshot_20231020-114933.jpg](https://github.com/zingolabs/zingolib/assets/37910384/609b2bfa-74d2-45d9-b916-5f4fa93eb300)

In the images you can see that Zingo PC and YWalllet show two and more transactions than Zingo Mobile.

![Screenshot_20231020-112000.jpg](https://github.com/zingolabs/zingolib/assets/37910384/050f17b1-9194-4aac-a230-30db1f821a92)

![IMG_20231020_123304_241.png](https://github.com/zingolabs/zingolib/assets/37910384/4236f3df-61d2-4d6d-9b67-d22bf63666c2)

The fact that in this example the transactions do appear in Zingo PC does not mean that it does not fail there, as I have reported in the test room in Matrix, this error also happens in Zingo PC.

2. **Transaction details change**

This error has been reported before, after synchronization the transactions may show a correct amount and fee, but when you close and open the wallet again the amount and fee change to a very different, extremely large amount.

Before:

![Screenshot_20231020-103912.jpg](https://github.com/zingolabs/zingolib/assets/37910384/1a5952b2-9eb3-4e26-95f9-89d839b30239)

TXID: 5977961...

After:

![Screenshot_20231020-105704.jpg](https://github.com/zingolabs/zingolib/assets/37910384/5e9d2e74-4f83-48cf-af1a-d61725b7220a)

TXID: 5877961...

3. **Balance disappears**

Just like the errors mentioned above, the wallet may show a correct balance when catching up with the synchronization, but when opening and closing the wallet and the balance usually changes, and may even be zero.

![Screenshot_20231020-114449.jpg](https://github.com/zingolabs/zingolib/assets/37910384/d283f417-1084-40b2-a903-b092bf9d16f0)

![Screenshot_20231020-114454.jpg](https://github.com/zingolabs/zingolib/assets/37910384/35f5ff20-c68d-4bde-b575-9666e5f1a7aa)

![Screenshot_20231020-114937.jpg](https://github.com/zingolabs/zingolib/assets/37910384/64936c13-a10c-4fe5-b06a-44341c817161)

See that Zingo PC and YWallet show the correct balance, also it was so before closing and opening the application.

![Screenshot_20231020-123243.jpg](https://github.com/zingolabs/zingolib/assets/37910384/134b6522-9864-426c-aa24-344ec30076a5)

![IMG_20231020_123304_241.png](https://github.com/zingolabs/zingolib/assets/37910384/ae362cc4-ed55-4988-961f-a21b543f95ea)

**I will be on the lookout for new changes for further testing.** 😎

**Comment by zancas** [comment] 2023-10-30 17:14
Is this behavior new to the feature branch?   Does it occur in production?

**Comment by zancas** [comment] 2023-10-30 17:15
@Edicksonjga which version of zingo are you testing?   Can you post a the version info?

**Comment by Edicksonjga** [comment] 2023-10-30 17:29
> @Edicksonjga which version of zingo are you testing?   Can you post a the version info?

I have never seen this error in production.

Version:![Screenshot_20231030-132754.jpg](https://github.com/zingolabs/zingolib/assets/37910384/7791505b-e518-479d-ae28-dc839e687e0a)

**Comment by fluidvanadium** [comment] 2023-11-03 16:16
@juanky201271 i think this bug is specific to mobile. can you help me write a test to catch it?

**Comment by juanky201271** [comment] 2023-11-03 16:43
of course...

**Comment by Edicksonjga** [comment] 2023-11-07 16:56
Make a transaction from Orchard to Sapling from the same wallet.

While the transaction was being confirmed I closed and opened the terminal several times and the transaction was always there as Unconfirmed.

After the transaction was confirmed I used the `Balance` command and it showed the correct balance in Sapling and Orchard, but when using summaries the transaction was still showing as Unconfirmed even though it already had more than 10 confirmations.

I closed (directly from the X) and opened the terminal to re-run zingo-cli and when using `summaries` the transaction no longer appears and the current balance is wrong.

version: mob-prerelease-1.3.0-207-g1fe99c4b-dirty

**Comment by Edicksonjga** [comment] 2023-11-07 16:58
I also performed the same test by shielding the balance and the same thing happened.

The last transaction disappears and the balance is incorrect.

I will test soon with a new version of zingolib.

**Comment by fluidvanadium** [comment] 2023-11-07 18:03
> Make a transaction from Orchard to Sapling from the same wallet.
> 
> While the transaction was being confirmed I closed and opened the terminal several times and the transaction was always there as Unconfirmed.
> 
> After the transaction was confirmed I used the `Balance` command and it showed the correct balance in Sapling and Orchard, but when using summaries the transaction was still showing as Unconfirmed even though it already had more than 10 confirmations.
> 
> I closed (directly from the X) and opened the terminal to re-run zingo-cli and when using `summaries` the transaction no longer appears and the current balance is wrong.
> 
> version: mob-prerelease-1.3.0-207-g1fe99c4b-dirty

my experience was similar
pressing ctrl-c or quitting led to a temporary forgetting of the new transaction.
then it reappeared. still unconfirmed
at this point, balance was incorrect. it showed a new spendable orchard change note but the original note was not marked as spent

then the note confirmed on the block explorer, but wasnt marked as confirmed in zingocli. until i used rescan

**Comment by Oscar-Pepper** [comment] 2023-11-07 21:23
while waiting for my orchard to sapling send to self to confirm i `ctrl-c` and relaunch zingo-cli and call summaries and balance:
```
(main) Block:2289020 (type 'help') >> summaries
[
  {
    "amount": 100000,
    "block_height": 2289009,
    "datetime": 1699391520,
    "kind": "Received",
    "memos": [],
    "pool": "Orchard",
    "price": null,
    "txid": "24add5a6f8fc36de731fc62f4ed8d0aa6ee92b5b29793d58625bf4f4aede3bd9",
    "unconfirmed": false
  },
  {
    "amount": 10000,
    "block_height": 2289020,
    "datetime": 1699391978,
    "kind": "Fee",
    "memos": [],
    "pool": "",
    "price": null,
    "txid": "eea4d27a1e5f65f053f156738d96341bb57ddc7cd0f90ffc54d1f5925cbd6ac4",
    "unconfirmed": true
  }
]
(main) Block:2289020 (type 'help') >> balance
{
  "sapling_balance": 20000,
  "verified_sapling_balance": 0,
  "spendable_sapling_balance": 0,
  "unverified_sapling_balance": 20000,
  "orchard_balance": 170000,
  "verified_orchard_balance": 100000,
  "unverified_orchard_balance": 70000,
  "spendable_orchard_balance": 100000,
  "transparent_balance": 0
}
(main) Block:2289020 (type 'help') >>
```

is this normal behaviour that we see the orchard change from a send get added to our pre-send balance?
or is this related to this bug?

**Comment by AloeareV** [comment] 2023-11-07 22:06
> is this known behaviour that we see the orchard change from a send get added to our pre-send balance? or is this related to this bug?

It's a (I think known? It happened to me during testing today, at least) aspect of this bug that we get the change added and not the spend subtracted.

**Comment by juanky201271** [comment] 2023-11-08 17:53
This video is interesting because you can see how appears the wrong amount in the first tx, change from send-to-self fee 0.0001 to 0.00032.
As you can see, the tx is correct when the App is restarted (stored in device) but when the App connects with the server, gets the wrong value...

https://github.com/zingolabs/zingolib/assets/43755989/474fde51-96df-4308-b64c-13d2bbe2afb5

**Comment by zancas** [comment] 2023-11-14 17:19
I believe that the bugs tracked by this issue are either fixed, or tracked elsewhere?

**Comment by Edicksonjga** [comment] 2023-11-14 17:34
> I believe that the bugs tracked by this issue are either fixed, or tracked elsewhere?

Until the last time I tested bug 1. it was half fixed, yes, the transaction no longer disappears, but still the transaction still shows up as confirmed and not as a transaction that is in the process of being mined.

Bug 2. was still present, the details of some transactions sometimes change, showing the fee as the amount sent or vice versa.

And error 3. I have not seen it again, what still happens is the duplicate balance when the transaction being processed is to shield balance, but this error is old, it even happens in the Production version.

Finally, the bug related to the incorrect balance in sapling when the background synchronization fails or the internet connection fails has not been fixed yet. @zancas

**Comment by Oscar-Pepper** [comment] 2023-11-14 17:56
so to clarfiy this still exists:
"Transaction details change
This error has been reported before, after synchronization the transactions may show a correct amount and fee, but when you close and open the wallet again the amount and fee change to a very different, extremely large amount."

do you still see extremely large amounts in the latest prerelease version?
and details on how we can write a test specifically for this would be really helpful!
thanks!

**Comment by Edicksonjga** [comment] 2023-11-14 18:53
> so to clarfiy this still exists:
> "Transaction details change
> This error has been reported before, after synchronization the transactions may show a correct amount and fee, but when you close and open the wallet again the amount and fee change to a very different, extremely large amount."

No, I have not seen extremely large amounts anymore. I have only seen that in auto-ship transactions you can see that the amount is equal to the fee and then when closing and opening you can see that the amount is equal to the total minus the fee.

I don't see it as a "big bug", but it should be the same for everything and not be changing from one to another. @Oscar-Pepper

**Comment by Oscar-Pepper** [comment] 2023-11-14 21:28
OK thanks I will try to produce a test to help narrow this down tomorrow

**Comment by juanky201271** [comment] 2023-11-14 23:05
> > so to clarfiy this still exists:
> > "Transaction details change
> > This error has been reported before, after synchronization the transactions may show a correct amount and fee, but when you close and open the wallet again the amount and fee change to a very different, extremely large amount."
> 
> No, I have not seen extremely large amounts anymore. I have only seen that in auto-ship transactions you can see that the amount is equal to the fee and then when closing and opening you can see that the amount is equal to the total minus the fee.
> 
> I don't see it as a "big bug", but it should be the same for everything and not be changing from one to another. @Oscar-Pepper

I sent to @Edicksonjga a new APK with the last commit in dev of zingolib... and I think this bug is fixed, Can you confirm it @Edicksonjga ?

**Comment by Edicksonjga** [comment] 2023-11-14 23:26
> ?

Today before going to sleep I'll do the test and pass my answer here and there... @juanky201271

**Comment by zancas** [comment] 2023-11-16 16:16
Hi!  @Edicksonjga @juanky201271 @fluidvanadium @AloeareV @Oscar-Pepper  What's the status of this issue?

**Comment by zancas** [comment] 2023-11-16 16:17
This issue is listed here:  https://github.com/zingolabs/zingolib/milestone/1

**Closed** 2023-11-16 16:38 UTC
Labels: bug
