### ISSUE TITLE
regtest mode isn't working for me

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#51] opened 2022-07-21 23:45 UTC
I ran `cargo build` against this commit:
64ae88b494c680597dfcdb1b0bca776830458828

Then I ran the following (after symlinking as directed in the README):

```
./target/debug/zingo-cli --regtest --data-dir regtest/datadir/zingo --server=127.0.0.1:9067
zcashd datadir: --datadir=/home/mherder/src/zingolabs/zingolibs/dev/regtest/datadir/zcash/
zcashd conf file: --conf=/home/mherder/src/zingolabs/zingolibs/dev/regtest/conf/zcash.conf
zcashd is starting in regtest mode, please standby about 10 seconds...
zcashd start section completed, zcashd should be running.
Standby, lightwalletd is about to start. This should only take a moment.
Using config file: /home/mherder/src/zingolabs/zingolibs/dev/regtest/conf/lightwalletdconf.yml
Starting insecure server
lwd start section completed, lightwalletd should be running!
Standby, Zingo-cli should be running in regtest mode momentarily...
Error during startup:Error with response: Status { code: Unavailable, message: "error trying to connect: tcp connect error: Connection refused (os error 111)", source: Some(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))) }
If you repeatedly run into this issue, you might have to restore your wallet from your seed phrase.
```

**Comment by dannasessha** [comment] 2022-07-22 03:08
I see this, I am attempting to engage in support on a more synchonous channel.

My own build of `64ae88` is working locally.

**Comment by dannasessha** [comment] 2022-07-22 03:42
My first thought is that the wait times to load the daemons are not sufficient with the combination of hardware and other loads on the system's resources. This type of issue should be fixed with #33 and #36 fixes, which is currently what I'm working on.

Until then you could patch the wait times to be longer, which is not great, but before the feature is ready it seems like a simple solution to get things working. You'll want to make sure all background daemons are manually killed that were spawned by previous attempts.

We should also find out exactly which versions of `zcashd` and `lightwalletd` we're making our binaries from if the problem persists past the above to try to isolate the issue.

**Comment by zancas** [comment] 2022-07-22 15:50
It turns out that it's looking for parameters.

**Comment by dannasessha** [comment] 2022-07-22 19:08
> It turns out that it's looking for parameters.

Could you elaborate, please?

**Comment by dannasessha** [comment] 2022-07-22 23:41
As this issue was caused by an error with `zcashd` booting, we will follow up with #27 !

**Closed by dannasessha** 2022-07-22 23:41 UTC
